name: Safe Settings Sync
on:
  # once per day at midnight
  schedule:
    - cron: "0 0 * * *" 
  # Or if triggered manually
  workflow_dispatch: {}
  # or on merge to main
  push:
    branches:
      - main

jobs:
  sync-safe-settings:
    runs-on: ubuntu-latest
    env:
      # Version/tag of github/safe-settings repo to use:
      SAFE_SETTINGS_VERSION: 2.1.14
      # Path on GHA runner box where safe-settings code downloaded to:
      SAFE_SETTINGS_CODE_DIR: ${{ github.workspace }}/.safe-settings-code
    steps:
      # Self-checkout of 'admin' repo for access to safe-settings config:
      - uses: actions/checkout@v4
      
      - name: Echo Environment Variables
        run: |
          echo "GH_ORG: ${{ github.repository_owner }}"
      
      - name: Echo Environment Variables 2
        run: |
          echo "APP_ID: ${{ vars.SAFE_SETTINGS_APP_ID}}"

      # Checkout of safe-settings repo for running full sync:
      - uses: actions/checkout@v4
        with:
          repository: github/safe-settings
          ref: 2.1.14
          path: ${{ github.workspace }}/.safe-settings-code
      - uses: actions/setup-node@v4
      - run: npm install
        working-directory: ${{ github.workspace }}/.safe-settings-code
      - run: npm run full-sync
        working-directory: ${{ github.workspace }}/.safe-settings-code
        env:
          GH_ORG: ${{ github.repository_owner }}
          APP_ID: ${{ vars.SAFE_SETTINGS_APP_ID }}
          PRIVATE_KEY: ${{ secrets.SAFE_SETTINGS_PRIVATE_KEY }}
          GITHUB_CLIENT_ID: ${{ vars.SAFE_SETTINGS_GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.SAFE_SETTINGS_GITHUB_CLIENT_SECRET }}
          BLOCK_REPO_RENAME_BY_HUMAN: true